### ISSUE TITLE
[question]请问什么是AntV上层？ 指的是适用于AntV的G6、X6、F2、L7等所有AntV产品的图是吗？

### ISSUE THREAD

**Issue by liaodalin19903** [antvis/graphlib#15]
> @antvis/graphlib是一个包含方便的图结构，图算法，以及其他操作图的方法的图库，为 AntV 上层提供相应的图基础能力。

有几个问题请问一下：
1、什么是图结构？
2、什么是AntV上层？ 指的是适用于AntV的G6、X6、F2、L7等所有AntV产品的图是吗？

**Comment by hustcc** [comment]
主要指 G6 X6 图数据的可视化相关的模块～
